name: Atualizar Conteúdo

on:
  schedule:
    # Define a frequência de execução uma vez por dia, todos os dias, às 01:17 da manhã
    - cron: '17 1 * * *'

jobs:
  extrair-conteudo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Checkout Node.js
        uses: actions/checkout@v4
        with:
          node-version: 18

      - name: Instalar Dependências
        run: npm install puppeteer

      - name: Extrair Conteúdo
        run: |
          node .github/workflows/extract.js
          git config --global user.email "rodrigomgraca@ua.pt"
          git config --global user.name "rodrigograc4"
          git add conteudo.html
          git commit -m "Atualizar conteúdo.html"
          git push
